---

# https://nodejs.org/dist/v4.1.1/node-v4.1.1-linux-x64.tar.gz

- get_url: url=https://nodejs.org/dist/{{ nodejs_version }}/node-{{ nodejs_version }}-linux-x64.tar.gz mode=0644 validate_certs=False
  args:
      dest: /tmp/node-{{ nodejs_version }}-linux-x64.tar.gz

# Could add a sha256sum at this point ...

- unarchive: src=/tmp/node-{{ nodejs_version }}-linux-x64.tar.gz dest=/usr/local
  args:
    creates: /usr/local/{{ nodejs_build_path }}-linux-x64

- file: src=/usr/local/{{ nodejs_build_path }}-linux-x64 dest=/usr/local/nodejs
  args:
    owner: root
    group: root
    state: link

- file: src=/usr/local/nodejs/bin/npm dest=/usr/bin/npm
  args:
    owner: root
    group: root
    state: link

- file: src=/usr/local/nodejs/bin/node dest=/usr/bin/node
  args:
    owner: root
    group: root
    state: link

# http://docs.ansible.com/ansible/lineinfile_module.html
- lineinfile: dest=/etc/profile line="export PATH=$PATH:/usr/local/nodejs/bin"
  args:
    state: present

# Path for ZSH (if available)
- stat: path=/etc/zsh/zlogin
  register: nodejs_zlogin

- lineinfile: dest=/etc/zsh/zlogin line="export PATH=$PATH:/usr/local/nodejs/bin"
  when: nodejs_zlogin.stat.exists == True
  args:
    state: present